/**
 * Copyright (c) 2026 Bastian Kleinschmidt
 * Licensed under the GNU Affero General Public License v3.0.
 * See LICENSE.txt for details.
 */

(() => {
	'use strict'

	const THUNDERBIRD_ATTACHMENT_AUTOMATION_GUIDE_URL = 'https://github.com/nc-connector/Server_Backend/blob/main/Doku/admin.md#thunderbird-attachment-automation-prerequisite'
	const SHARE_HTML_TEMPLATE_KEY = 'share_html_block_template'
	const SHARE_PASSWORD_TEMPLATE_KEY = 'share_password_template'
	const TALK_INVITATION_TEMPLATE_KEY = 'talk_invitation_template'
	const TALK_INVITATION_TEMPLATE_FORMAT_KEY = 'talk_invitation_template_format'
	const EMAIL_SIGNATURE_TEMPLATE_KEY = 'email_signature_template'
	const SETTING_META = {
		share_base_directory: {
			label: 'Base directory',
			tooltip: ['Files are stored below this folder (for example "NC Connector").'],
		},
		share_name_template: {
			label: 'Share name',
			tooltip: ['Default share name used by the mail add-on.'],
		},
		share_permission_upload: {
			label: 'Upload/Create',
			tooltip: [
				'These values are defaults for newly created shares.',
				'They can be changed in the share wizard.',
				'In attachment mode recipients always have read-only access.',
			],
		},
		share_permission_edit: {
			label: 'Edit',
			tooltip: [
				'These values are defaults for newly created shares.',
				'They can be changed in the share wizard.',
				'In attachment mode recipients always have read-only access.',
			],
		},
		share_permission_delete: {
			label: 'Delete',
			tooltip: [
				'These values are defaults for newly created shares.',
				'They can be changed in the share wizard.',
				'In attachment mode recipients always have read-only access.',
			],
		},
		share_set_password: {
			label: 'Set password',
			tooltip: ['Defines whether new shares should use a password by default.'],
		},
		share_send_password_separately: {
			label: 'Send password separately',
			tooltip: ['Send password in a separate follow-up email.'],
		},
		share_send_password_mode: {
			label: 'Password mode',
			tooltip: ['Controls how separate share passwords are delivered.'],
		},
		share_secrets_expire_days: {
			label: 'Nextcloud Secrets link expiry (days)',
			tooltip: ['Defines how long generated Secrets links stay valid.'],
		},
		share_expire_days: {
			label: 'Expiration (days)',
			tooltip: ['Defines the default lifetime in days for new shares.'],
		},
		attachments_always_via_ncconnector: {
			label: 'Always share attachments via NC Connector',
			tooltip: [
				'New attachments are removed from the compose email and handled via NC Connector.',
				'The share wizard starts directly in the file step.',
				'The final message contains share links instead of physical attachments.',
				'Thunderbird only: if NC Connector attachment automation should be the only active compose flow, also disable Thunderbird\'s own attachment prompts centrally.',
			],
			tooltipLinkLabel: 'Read the Thunderbird prerequisite in the admin guide',
			tooltipLinkHref: THUNDERBIRD_ATTACHMENT_AUTOMATION_GUIDE_URL,
		},
		attachments_min_size_mb: {
			label: 'Offer upload for files larger than (MB)',
			tooltip: [
				'The total size of all attachments is evaluated.',
				'When exceeded, files can be shared via NC Connector or the latest selected attachment group can be removed.',
				'The remove action reduces the email below the threshold again.',
				'Thunderbird only: if NC Connector attachment automation should be the only active compose flow, also disable Thunderbird\'s own attachment prompts centrally.',
			],
			tooltipLinkLabel: 'Read the Thunderbird prerequisite in the admin guide',
			tooltipLinkHref: THUNDERBIRD_ATTACHMENT_AUTOMATION_GUIDE_URL,
		},
		share_html_block_template: {
			label: 'Email share template',
			tooltip: [
				'HTML template used for the share block inserted by mail clients.',
				'Use variables like {URL}, {PASSWORD}, {EXPIRATIONDATE}, {RIGHTS}, {NOTE}.',
			],
		},
		share_password_template: {
			label: 'Email password template',
			tooltip: [
				'Use this template for the separate password email.',
				'Available variable: {PASSWORD}.',
			],
		},
		language_share_html_block: {
			label: 'Language in share HTML block',
			tooltip: ['Controls the language of the inserted share HTML block.'],
		},
		language_talk_description: {
			label: 'Language in Talk description text',
			tooltip: ['Controls the language of the Talk text block in calendar events.'],
		},
		talk_invitation_template_format: {
			label: 'Talk invitation output',
			tooltip: ['Controls whether the Talk template is delivered to mail clients as HTML or as cleaned plain text.'],
		},
		talk_invitation_template: {
			label: 'Talk invitation template',
			tooltip: [
				'Use this template for the Talk invitation text.',
				'Available variables: {MEETING_URL}, {PASSWORD}.',
			],
		},
		talk_generate_password: {
			label: 'Generate password for meetings',
			tooltip: ['Automatically generates a password when a Talk room is created.'],
		},
		talk_title: {
			label: 'Title',
			tooltip: ['Default title for newly created Talk rooms.'],
		},
		talk_lobby_active: {
			label: 'Lobby active until start time',
			tooltip: [
				'Participants stay in the lobby (waiting room) before the meeting starts and cannot enter the call yet.',
				'Joining is possible only at the configured start time (or when a moderator opens the lobby).',
				'Useful to prevent participants from joining too early.',
			],
		},
		talk_show_in_search: {
			label: 'Show in search',
			tooltip: [
				'The room is visible in Talk search.',
				'This makes rooms easier to find, but they are discoverable by users.',
			],
		},
		talk_add_users: {
			label: 'Add users',
			tooltip: [
				'Internal Nextcloud users are added directly to the room.',
				'The room appears in Nextcloud Talk immediately.',
			],
		},
		talk_add_guests: {
			label: 'Add guests',
			tooltip: [
				'Guests are also added directly to the room.',
				'They receive a separate (additional) email with a personal access link.',
			],
		},
		talk_set_password: {
			label: 'Set password',
			tooltip: ['Defines whether new Talk rooms should use a password by default.'],
		},
		talk_delete_room_on_event_delete: {
			label: 'Delete Talk room when deleting a saved event',
			tooltip: [
				'Only saved events with NC Connector Talk metadata are eligible.',
				'Generic Talk links in location or URL fields are ignored by the mail clients.',
				'Unsaved event cleanup remains active independently.',
			],
		},
		talk_room_type: {
			label: 'Room type',
			tooltip: [
				'Event conversation: time-limited, lightweight, self-cleaning.',
				'Group conversation: persistent with full history.',
			],
		},
		email_signature_on_compose: {
			label: 'Add signature when composing',
			tooltip: ['Controls whether mail clients should add the centrally managed signature to new messages.'],
		},
		email_signature_on_reply: {
			label: 'Add signature when replying',
			tooltip: ['Controls whether mail clients should add the centrally managed signature to replies.'],
		},
		email_signature_on_forward: {
			label: 'Add signature when forwarding',
			tooltip: ['Controls whether mail clients should add the centrally managed signature to forwarded messages.'],
		},
		email_signature_template: {
			label: 'Email signature template',
			tooltip: [
				'HTML signature template delivered to mail clients.',
				'Available variables: {NAME}, {EMAIL}, {PHONE}, {PHONE_MOBILE}, {ABOUT}, {FUNCTION}, {ORGANISATION}, {CUSTOM1}, {CUSTOM2}.',
				'The {ABOUT} variable preserves line breaks.',
			],
		},
		email_signature_email_address: {
			label: 'Signature email address',
			tooltip: [
				'Overrides the profile email used for {EMAIL} and sender matching.',
				'Use inherit to keep the Nextcloud profile email.',
			],
		},
		email_signature_phone_mobile: {
			label: 'Mobile phone',
			tooltip: ['Optional value for {PHONE_MOBILE}.'],
		},
		email_signature_custom1: {
			label: 'Custom 1',
			tooltip: ['Optional value for {CUSTOM1}.'],
		},
		email_signature_custom2: {
			label: 'Custom 2',
			tooltip: ['Optional value for {CUSTOM2}.'],
		},
	}
	const ENUM_OPTION_LABELS = {
		share_send_password_mode: {
			plain: 'Plaintext',
			secrets: 'Nextcloud Secret Link',
		},
		talk_room_type: {
			event: 'Event conversation',
			group: 'Group conversation',
		},
		language_share_html_block: {
			ui_default: 'Default (UI)',
			custom: 'Custom',
			en: 'English',
			de: 'German',
			fr: 'French',
			zh_cn: 'Chinese (China)',
			zh_tw: 'Chinese (Taiwan)',
			it: 'Italian',
			ja: 'Japanese',
			nl: 'Dutch',
			pl: 'Polish',
			pt_br: 'Portuguese (Brazil)',
			pt_pt: 'Portuguese (Portugal)',
			ru: 'Russian',
			es: 'Spanish',
			cs: 'Czech',
			hu: 'Hungarian',
		},
		language_talk_description: {
			ui_default: 'Default (UI)',
			custom: 'Custom',
			en: 'English',
			de: 'German',
			fr: 'French',
			zh_cn: 'Chinese (China)',
			zh_tw: 'Chinese (Taiwan)',
			it: 'Italian',
			ja: 'Japanese',
			nl: 'Dutch',
			pl: 'Polish',
			pt_br: 'Portuguese (Brazil)',
			pt_pt: 'Portuguese (Portugal)',
			ru: 'Russian',
			es: 'Spanish',
			cs: 'Czech',
			hu: 'Hungarian',
		},
		talk_invitation_template_format: {
			html: 'HTML',
			plain_text: 'Plain Text',
		},
	}
	const TEMPLATE_TRANSLATION_LOCALES = [
		'en',
		'de',
		'fr',
		'cs',
		'es',
		'hu',
		'it',
		'ja',
		'nl',
		'pl',
		'pt_br',
		'pt_pt',
		'ru',
		'zh_cn',
		'zh_tw',
	]
	const TEMPLATE_TRANSLATION_PHRASES = {
		[SHARE_HTML_TEMPLATE_KEY]: {
			share_intro_1: {
				en: 'The files have been provided securely and in a privacy-compliant manner via Nextcloud.',
				de: 'Die Dateien wurden sicher und datenschutzkonform über Nextcloud bereitgestellt.',
				fr: 'Les fichiers ont été fournis de manière sécurisée et conforme à la protection des données via Nextcloud.',
				cs: 'Soubory byly prostřednictvím Nextcloudu poskytnuty bezpečně a v souladu s ochranou osobních údajů.',
				es: 'Los archivos se han proporcionado de forma segura y conforme a la protección de datos a través de Nextcloud.',
				hu: 'A fájlok biztonságosan és az adatvédelemnek megfelelően, Nextcloudon keresztül kerültek megosztásra.',
				it: 'I file sono stati forniti in modo sicuro e conforme alla protezione dei dati tramite Nextcloud.',
				ja: 'ファイルは Nextcloud を通じて安全かつプライバシーに配慮した形で提供されています。',
				nl: 'De bestanden zijn veilig en privacyconform via Nextcloud beschikbaar gesteld.',
				pl: 'Pliki zostały udostępnione przez Nextcloud w sposób bezpieczny i zgodny z zasadami ochrony prywatności.',
				pt_br: 'Os arquivos foram disponibilizados com segurança e em conformidade com a privacidade por meio do Nextcloud.',
				pt_pt: 'Os ficheiros foram disponibilizados de forma segura e em conformidade com a privacidade através do Nextcloud.',
				ru: 'Файлы были предоставлены через Nextcloud безопасно и с соблюдением требований конфиденциальности.',
				zh_cn: '这些文件已通过 Nextcloud 以安全且符合隐私保护要求的方式提供。',
				zh_tw: '這些檔案已透過 Nextcloud 以安全且符合隱私保護要求的方式提供。',
			},
			share_intro_2: {
				en: 'You can download them using the link below.',
				de: 'Der Download ist über den untenstehenden Link möglich.',
				fr: 'Le téléchargement est possible via le lien ci-dessous.',
				cs: 'Stahování je možné přes níže uvedený odkaz.',
				es: 'La descarga es posible mediante el enlace que aparece a continuación.',
				hu: 'A letöltés az alábbi hivatkozáson érhető el.',
				it: 'Il download è possibile tramite il link qui sotto.',
				ja: 'ダウンロードは以下のリンクから可能です。',
				nl: 'Downloaden is mogelijk via de onderstaande link.',
				pl: 'Pobieranie jest możliwe za pomocą poniższego linku.',
				pt_br: 'O download pode ser feito pelo link abaixo.',
				pt_pt: 'A transferência pode ser feita através da ligação abaixo.',
				ru: 'Загрузка возможна по ссылке ниже.',
				zh_cn: '可通过下方链接下载。',
				zh_tw: '可透過下方連結下載。',
			},
			download_link: {
				en: 'Download link',
				de: 'Download-Link',
				fr: 'Lien de téléchargement',
				cs: 'Odkaz ke stažení',
				es: 'Enlace de descarga',
				hu: 'Letöltési hivatkozás',
				it: 'Link per il download',
				ja: 'ダウンロードリンク',
				nl: 'Downloadlink',
				pl: 'Link do pobrania',
				pt_br: 'Link para download',
				pt_pt: 'Ligação para download',
				ru: 'Ссылка для скачивания',
				zh_cn: '下载链接',
				zh_tw: '下載連結',
			},
			password: {
				en: 'Password',
				de: 'Passwort',
				fr: 'Mot de passe',
				cs: 'Heslo',
				es: 'Contraseña',
				hu: 'Jelszó',
				it: 'Password',
				ja: 'パスワード',
				nl: 'Wachtwoord',
				pl: 'Hasło',
				pt_br: 'Senha',
				pt_pt: 'Palavra-passe',
				ru: 'Пароль',
				zh_cn: '密码',
				zh_tw: '密碼',
			},
			expiration_date: {
				en: 'Expiration date',
				de: 'Ablaufdatum',
				fr: 'Date d’expiration',
				cs: 'Datum vypršení platnosti',
				es: 'Fecha de vencimiento',
				hu: 'Lejárati dátum',
				it: 'Data di scadenza',
				ja: '有効期限',
				nl: 'Vervaldatum',
				pl: 'Data wygaśnięcia',
				pt_br: 'Data de expiração',
				pt_pt: 'Data de expiração',
				ru: 'Дата истечения срока',
				zh_cn: '到期日期',
				zh_tw: '到期日期',
			},
			rights: {
				en: 'Rights',
				de: 'Berechtigungen',
				fr: 'Droits',
				cs: 'Oprávnění',
				es: 'Permisos',
				hu: 'Jogosultságok',
				it: 'Permessi',
				ja: '権限',
				nl: 'Rechten',
				pl: 'Uprawnienia',
				pt_br: 'Permissões',
				pt_pt: 'Permissões',
				ru: 'Права',
				zh_cn: '权限',
				zh_tw: '權限',
			},
			nextcloud_footer: {
				en: 'is a solution for secure email and data exchange.',
				de: 'ist eine Lösung für sicheren E-Mail- und Datenaustausch.',
				fr: 'est une solution pour l’échange sécurisé d’e-mails et de données.',
				cs: 'je řešení pro bezpečnou výměnu e-mailů a dat.',
				es: 'es una solución para el intercambio seguro de correos electrónicos y datos.',
				hu: 'biztonságos e-mail- és adatcserére szolgáló megoldás.',
				it: 'è una soluzione per lo scambio sicuro di e-mail e dati.',
				ja: 'は、安全なメールとデータ交換のためのソリューションです。',
				nl: 'is een oplossing voor veilige uitwisseling van e-mail en gegevens.',
				pl: 'to rozwiązanie do bezpiecznej wymiany wiadomości e-mail i danych.',
				pt_br: 'é uma solução para troca segura de e-mails e dados.',
				pt_pt: 'é uma solução para a troca segura de e-mails e dados.',
				ru: '— это решение для безопасного обмена электронной почтой и данными.',
				zh_cn: '是安全电子邮件和数据交换的解决方案。',
				zh_tw: '是安全電子郵件與資料交換的解決方案。',
			},
		},
		[SHARE_PASSWORD_TEMPLATE_KEY]: {
			password_intro: {
				en: 'Here is your password for the sent share.',
				de: 'Hier ist Ihr Passwort zur gesendeten Freigabe.',
				fr: 'Voici votre mot de passe pour le partage envoyé.',
				cs: 'Zde je vaše heslo k odeslanému sdílení.',
				es: 'Aquí tiene su contraseña para la compartición enviada.',
				hu: 'Itt találja az elküldött megosztáshoz tartozó jelszót.',
				it: 'Ecco la password per la condivisione inviata.',
				ja: '送信された共有に対するパスワードはこちらです。',
				nl: 'Hier is uw wachtwoord voor de verzonden share.',
				pl: 'Oto hasło do wysłanego udostępnienia.',
				pt_br: 'Aqui está sua senha para o compartilhamento enviado.',
				pt_pt: 'Aqui está a sua palavra-passe para a partilha enviada.',
				ru: 'Вот ваш пароль для отправленной публикации.',
				zh_cn: '这是您已发送共享的密码。',
				zh_tw: '這是您已傳送分享的密碼。',
			},
			password: {
				en: 'Password',
				de: 'Passwort',
				fr: 'Mot de passe',
				cs: 'Heslo',
				es: 'Contraseña',
				hu: 'Jelszó',
				it: 'Password',
				ja: 'パスワード',
				nl: 'Wachtwoord',
				pl: 'Hasło',
				pt_br: 'Senha',
				pt_pt: 'Palavra-passe',
				ru: 'Пароль',
				zh_cn: '密码',
				zh_tw: '密碼',
			},
		},
		[TALK_INVITATION_TEMPLATE_KEY]: {
			meeting_takes_place: {
				en: 'This meeting takes place in Nextcloud Talk',
				de: 'Dieses Meeting findet in Nextcloud Talk statt',
				fr: 'Cette réunion se déroule dans Nextcloud Talk',
				cs: 'Tato schůzka probíhá v Nextcloud Talk',
				es: 'Esta reunión se realiza en Nextcloud Talk',
				hu: 'Ez a megbeszélés a Nextcloud Talkban zajlik',
				it: 'Questa riunione si svolge in Nextcloud Talk',
				ja: 'このミーティングは Nextcloud Talk で行われます',
				nl: 'Deze vergadering vindt plaats in Nextcloud Talk',
				pl: 'To spotkanie odbywa się w Nextcloud Talk',
				pt_br: 'Esta reunião acontece no Nextcloud Talk',
				pt_pt: 'Esta reunião decorre no Nextcloud Talk',
				ru: 'Эта встреча проходит в Nextcloud Talk',
				zh_cn: '本次会议在 Nextcloud Talk 中进行',
				zh_tw: '此會議在 Nextcloud Talk 中進行',
			},
			join_meeting_now: {
				en: 'Meeting link:',
				de: 'Meeting-Link:',
				fr: 'Lien de réunion :',
				cs: 'Odkaz na schůzku:',
				es: 'Enlace de la reunión:',
				hu: 'Megbeszélés hivatkozása:',
				it: 'Link della riunione:',
				ja: 'ミーティングリンク:',
				nl: 'Vergaderlink:',
				pl: 'Link do spotkania:',
				pt_br: 'Link da reunião:',
				pt_pt: 'Ligação da reunião:',
				ru: 'Ссылка на встречу:',
				zh_cn: '会议链接：',
				zh_tw: '會議連結：',
			},
			password_colon: {
				en: 'Password:',
				de: 'Passwort:',
				fr: 'Mot de passe :',
				cs: 'Heslo:',
				es: 'Contraseña:',
				hu: 'Jelszó:',
				it: 'Password:',
				ja: 'パスワード:',
				nl: 'Wachtwoord:',
				pl: 'Hasło:',
				pt_br: 'Senha:',
				pt_pt: 'Palavra-passe:',
				ru: 'Пароль:',
				zh_cn: '密码：',
				zh_tw: '密碼：',
			},
			need_help: {
				en: 'Need help?',
				de: 'Benötigen Sie Hilfe?',
				fr: 'Besoin d’aide ?',
				cs: 'Potřebujete pomoc?',
				es: '¿Necesita ayuda?',
				hu: 'Segítségre van szüksége?',
				it: 'Hai bisogno di aiuto?',
				ja: 'ヘルプが必要ですか？',
				nl: 'Hulp nodig?',
				pl: 'Potrzebujesz pomocy?',
				pt_br: 'Precisa de ajuda?',
				pt_pt: 'Precisa de ajuda?',
				ru: 'Нужна помощь?',
				zh_cn: '需要帮助吗？',
				zh_tw: '需要協助嗎？',
			},
		},
	}

	window.NCCBackendAdminSettingsMeta = {
		settingMeta: SETTING_META,
		enumOptionLabels: ENUM_OPTION_LABELS,
		templateTranslationLocales: TEMPLATE_TRANSLATION_LOCALES,
		templateTranslationPhrases: TEMPLATE_TRANSLATION_PHRASES,
	}
})()